
CREATE TABLE messages (

    id              integer generated by default as identity,
    message         varchar(255),
    type            varchar(255),
    age             integer,
    processed       boolean
)

